#!/usr/bin/env python3
"""
PDF document export for Bonifade Swarm agents.

Creates professional PDFs (proposals, quotes, SOWs, briefs) under data/exports/.
Files persist via the ./data Docker volume.
"""

from __future__ import annotations

import os
import re
import time
import uuid
from typing import Any, Dict, List, Optional

DATA_DIR = os.getenv("DATA_DIR", "/app/data")
if not os.path.exists(DATA_DIR) and os.path.exists("data"):
    DATA_DIR = "data"

EXPORTS_DIR = os.path.join(DATA_DIR, "exports")
COMPANY_NAME = os.getenv("COMPANY_NAME", "Bonifade Technologies")
COMPANY_WEBSITE = os.getenv("COMPANY_WEBSITE", "https://bonifadetechnologies.com")
COMPANY_EMAIL = os.getenv("COMPANY_OFFICIAL_EMAIL", "bonifadetechnologies@gmail.com")

# Prefer icon for PDF header; full wordmark available for covers
_ASSETS_CANDIDATES = [
    os.getenv("COMPANY_LOGO_PATH", "").strip(),
    "/app/assets/brand/logo-icon.jpeg",
    "/app/assets/logo-icon.jpeg",
    "/app/assets/brand/logo-512.png",
    "assets/brand/logo-icon.jpeg",
    "assets/logo-icon.jpeg",
    "assets/brand/logo-512.png",
    "assets/brand/logo-full.jpeg",
    "assets/logo-full.jpeg",
]


def resolve_logo_path() -> Optional[str]:
    for path in _ASSETS_CANDIDATES:
        if path and os.path.isfile(path):
            return path
    return None


def _ensure_exports() -> str:
    os.makedirs(EXPORTS_DIR, exist_ok=True)
    return EXPORTS_DIR


def _safe_filename(name: str) -> str:
    base = re.sub(r"[^a-zA-Z0-9._-]+", "_", (name or "document").strip())[:80]
    return base or "document"


def _latin1_safe(text: str) -> str:
    """Core PDF fonts are Latin-1; replace unsupported chars."""
    if text is None:
        return ""
    return (
        str(text)
        .replace("—", "-")
        .replace("–", "-")
        .replace("“", '"')
        .replace("”", '"')
        .replace("‘", "'")
        .replace("’", "'")
        .replace("•", "-")
        .replace("✓", "[ok]")
        .replace("→", "->")
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


def generate_pdf(
    title: str,
    body: str,
    doc_type: str = "document",
    client_name: str = "",
    filename: str = "",
    sections: Optional[List[Dict[str, str]]] = None,
    footer_note: str = "",
) -> Dict[str, Any]:
    """
    Generate a multi-page PDF.

    body: main markdown-ish text (paragraphs separated by blank lines; lines
          starting with '- ' or '* ' become bullets).
    sections: optional list of {"heading": "...", "body": "..."} appended after body.
    """
    try:
        from fpdf import FPDF
    except ImportError as e:
        return {
            "ok": False,
            "error": "fpdf2 not installed. Rebuild agent image (pip install fpdf2).",
            "detail": str(e),
        }

    _ensure_exports()
    stamp = time.strftime("%Y%m%d_%H%M%S")
    slug = _safe_filename(filename or f"{doc_type}_{client_name or title}_{stamp}")
    if not slug.lower().endswith(".pdf"):
        slug = f"{slug}.pdf"
    out_path = os.path.join(EXPORTS_DIR, slug)

    class SwarmPDF(FPDF):
        def header(self):
            logo = resolve_logo_path()
            start_y = 10
            text_x = self.l_margin
            if logo:
                try:
                    # Square icon on the left
                    self.image(logo, x=self.l_margin, y=start_y, h=14)
                    text_x = self.l_margin + 18
                except Exception:
                    text_x = self.l_margin

            self.set_xy(text_x, start_y)
            self.set_font("Helvetica", "B", 11)
            self.set_text_color(30, 30, 30)
            self.cell(0, 7, _latin1_safe(COMPANY_NAME), new_x="LMARGIN", new_y="NEXT")
            self.set_x(text_x)
            self.set_font("Helvetica", "", 8)
            self.set_text_color(90, 90, 90)
            self.cell(
                0,
                5,
                _latin1_safe(f"{COMPANY_WEBSITE}  |  {COMPANY_EMAIL}"),
                new_x="LMARGIN",
                new_y="NEXT",
            )
            self.set_y(max(self.get_y(), start_y + 16))
            self.ln(2)
            self.set_draw_color(40, 40, 40)
            y = self.get_y()
            self.line(self.l_margin, y, self.w - self.r_margin, y)
            self.ln(6)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            note = footer_note or "Generated by Bonifade Swarm — quotes only; payments handled by humans."
            self.cell(
                0,
                5,
                _latin1_safe(f"{note}  |  page {self.page_no()}"),
                align="C",
            )

    pdf = SwarmPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(left=15, top=28, right=15)
    pdf.add_page()

    # Title block
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(20, 20, 20)
    pdf.multi_cell(0, 10, _latin1_safe(title or "Document"))
    pdf.ln(2)

    meta = f"Type: {doc_type}"
    if client_name:
        meta += f"  |  Client: {client_name}"
    meta += f"  |  Date: {time.strftime('%Y-%m-%d')}"
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 5, _latin1_safe(meta))
    pdf.ln(4)

    usable_w = pdf.w - pdf.l_margin - pdf.r_margin

    def write_block(text: str):
        for raw_line in (text or "").splitlines():
            line = raw_line.rstrip()
            pdf.set_x(pdf.l_margin)
            if not line.strip():
                pdf.ln(3)
                continue
            if line.startswith("# "):
                pdf.set_font("Helvetica", "B", 14)
                pdf.set_text_color(20, 20, 20)
                pdf.multi_cell(usable_w, 8, _latin1_safe(line[2:].strip()))
                pdf.ln(1)
            elif line.startswith("## "):
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(30, 30, 30)
                pdf.multi_cell(usable_w, 7, _latin1_safe(line[3:].strip()))
                pdf.ln(1)
            elif line.lstrip().startswith(("- ", "* ")):
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(30, 30, 30)
                bullet = line.lstrip()[2:].strip()
                pdf.multi_cell(usable_w, 6, _latin1_safe(f"- {bullet}"))
            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(30, 30, 30)
                pdf.multi_cell(usable_w, 6, _latin1_safe(line))

    write_block(body or "")

    for section in sections or []:
        heading = (section or {}).get("heading") or (section or {}).get("title") or ""
        sbody = (section or {}).get("body") or (section or {}).get("content") or ""
        if heading:
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.multi_cell(0, 7, _latin1_safe(heading))
            pdf.ln(1)
        if sbody:
            write_block(sbody)

    pdf.output(out_path)

    return {
        "ok": True,
        "path": out_path,
        "filename": os.path.basename(out_path),
        "exports_dir": EXPORTS_DIR,
        "bytes": os.path.getsize(out_path),
        "doc_type": doc_type,
        "title": title,
        "logo": resolve_logo_path(),
        "note": "PDF saved on the host under ./data/exports/ (Docker volume).",
    }


def list_exports(limit: int = 20) -> Dict[str, Any]:
    _ensure_exports()
    files = []
    for name in sorted(os.listdir(EXPORTS_DIR), reverse=True):
        if not name.lower().endswith(".pdf"):
            continue
        path = os.path.join(EXPORTS_DIR, name)
        try:
            st = os.stat(path)
            files.append(
                {
                    "filename": name,
                    "path": path,
                    "bytes": st.st_size,
                    "modified_at": st.st_mtime,
                }
            )
        except OSError:
            continue
        if len(files) >= max(1, min(int(limit or 20), 100)):
            break
    return {"ok": True, "count": len(files), "exports": files, "dir": EXPORTS_DIR}
